# compositeアクション
# ファイル名はactionでないとダメ
name: Dump
description: |
  環境変数とgithubコンテキストをログへ出力します。
  ワークフローのデバッグに便利です。
inputs:
  enable-context:
    description: |
      githubコンテキストを出力するかどうか
    required: false
    default: true
outputs:
  dumped-date:
    value: ${{ steps.current.outputs.date }}
    description: |
      ダンプ日時
runs:
  using: composite
  steps:
    - run: printenv | sort
      shell: bash
    - run: echo "${CONTEXT}"
      shell: bash
      if: ${{ inputs.enable-context == 'true' }}
      env:
        CONTEXT: ${{ toJSON(github) }}
    - id: current
      run: echo "date=$(date)" >> "${GITHUB_OUTPUT}"
      shell: bash