name: Container Image Scan
on: workflow_dispatch

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: aquasecurity/trivy-action@0.23.0
        with:
          image-ref: nginx:1.11.0
          severity: CRITICAL, HIGH
          format: json
          exit-code: 1