name: Hello
on:
  push:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
      log-level:
        type: choice
        description: choice parameter sample
        options:
          - info
          - warn
          - error

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}, World"
      - uses: actions/checkout@v4
