name: Hello
run-name: Run by @${{ github.actor }}
on:
  schedule:
    - cron: '5 5 5 * *'
  push:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
      log-level:
        type: choice
        description: choice parameter sample
        options:
          - info
          - warn
          - error

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}, World"
      - uses: actions/checkout@v4
  built-in-function:
    runs-on: ubuntu-latest
    # https://docs.github.com/ja/actions/learn-github-actions/expressions
    env:
      FUNC_CONTAIN: ${{ contains('Hello Actions', 'Action') }}
      FUNC_STARTS_WITH: ${{ startsWith('Hello Actions', 'He') }}
      FUNC_ENDS_WITH: ${{ endsWith('Hello Actions', 'ons') }}
      FUNC_FORMAT: ${{ format('Hello {0} {1}', 'Actions', '!') }}
      FUNC_JOIN: ${{ join(github.event.issue.labels.*.name, ', ') }}
      FUNC_TO_JSON: ${{ toJSON(github) }}
    steps:
      - run: printenv | grep 'FUNC_'
